### ISSUE TITLE
Multi User enabled by default

### ISSUE THREAD

**Issue by Merith-TK** [ZeroNetX/ZeroNet#152]
### Step 1: Please describe your environment

  * ZeroNet version: `docker:` `canwsin/zeronet` as of 2-21-2022
  * Operating system: Windows 11 Host, Docker Container using WSL2 (effectively linux) backend
  * Web browser: Brave
  * Tor status: always
  * Opened port: Unsure
  * Special configuration: Required Special Config to work around bug

### Step 2: Describe the problem:
By default, the container run with multiuser plugin enabled,

this is my config for docker-compose
```yml
  zeronet:
    image: canewsin/zeronet:latest
    container_name: zeronet
    environment:
      - ENABLE_TOR=true
    restart: always
    ## For Some reason, modifying the command that is normally ran, causes
    ## issues with the container, so default to sh file that does the same
    ## thing as the command
    command: '/bin/sh /root/data/start.sh'
    ports:
      - 43110:43110
    volumes:
      - ./zeronet/:/root/data
```
this is start.sh
```sh
#!/bin/sh
if [ $ENABLE_TOR != "" ]; then
	tor&
fi

## This line is only required because of this bug, I have to remove the multiuser plugin directly to prevent it from loading
rm -rf /root/plugins/*Multiuser*

## zeronet.link because I have DNS and custom SSL Cert fekkery being performed on my system
python3 zeronet.py --ui_ip 0.0.0.0 --ui_host "zeronet.link" --fileserver_port 26117
```

I use a docker container with zeronet along with caddy, pi-hole dns, and an self signed SSL certificate to access zeronet from zeronet.link instead of the usual 127.0.0.1, just looks nicer also allows me to actually share the links

#### Steps to reproduce:

Use docker container

#### Observed Results:
Multiuser is enabled by default

#### Expected Results:
Multiuser to not be disabled
